config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  resources :books do
    member do
      post 'take'   # This creates the take_book_path
      post 'return' # If you have a return action as well
    end
  end
  # other routes...
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  validates :author, presence: true

  scope :available, -> { where(is_taken: [false, nil]) }

  def formatted_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  serialize :user_books, Array

  def get_books
    Book.where(is_taken: false)
  end

  def take_book(id)
    return "You can't take more than 2 books." if user_books.length >= 2
    book = Book.find_by(id: id)
    return "Book already taken." if book.is_taken
    book.update(is_taken: true)
    user_books << id
    save
    "Book taken successfully."
  end

  def return_book(id)
    book = Book.find_by(id: id)
    return "Book not found in your list." unless user_books.include?(id)
    book.update(is_taken: false)
    user_books.delete(id)
    save
    "Book returned successfully."
  end

  def my_books
    Book.where(id: user_books)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.available
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.is_taken = false  # Ensure new books are not taken by default
    if @book.save
      redirect_to books_path, notice: 'Book was successfully created.'
    else
      puts @book.errors.full_messages # For debugging
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Book was successfully destroyed.'
  end

  def take
    if @book.update(is_taken: true)
      redirect_to books_path, notice: 'Book was successfully taken.'
    else
      redirect_to books_path, alert: 'Unable to take the book.'
    end
  end

  def return
    if @book.update(is_taken: false)
      redirect_to books_path, notice: 'Book was successfully returned.'
    else
      redirect_to books_path, alert: 'Unable to return the book.'
    end
  end


  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :body, :is_taken)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @available_books = @user.get_books
    @my_books = @user.my_books
  end

  def take_book
    @user = User.find(params[:id])
    message = @user.take_book(params[:book_id])
    redirect_to @user, notice: message
  end

  def return_book
    @user = User.find(params[:id])
    message = @user.return_book(params[:book_id])
    redirect_to @user, notice: message
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with(model: @book, local: true, class: 'needs-validation', novalidate: true) do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control', required: true %>
    <div class="invalid-feedback">
      Please provide a title.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :author, class: 'form-label' %>
    <%= form.text_field :author, class: 'form-control', required: true %>
    <div class="invalid-feedback">
      Please provide an author.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :body, class: 'form-label' %>
    <%= form.text_area :body, class: 'form-control', rows: 5, required: true %>
    <div class="invalid-feedback">
      Please provide some text for the book.
    </div>
  </div>

  <div class="mb-3 form-check">
    <%= form.check_box :is_taken, class: 'form-check-input' %>
    <%= form.label :is_taken, class: 'form-check-label' %>
  </div>

  <%= form.submit 'Create Book', class: 'btn btn-primary' %>
<% end %>

app/views/books/edit.html.erb
<h1 class="mb-4">Edit book</h1>

<%= render 'form' %>

app/views/books/index.html.erb
<h1 class="mb-4">Available Books</h1>

<%= link_to 'New book', new_book_path, class: 'btn btn-primary btn-lg' %>

<% if @books.any? %>
  <% @books.each do |book| %>
    <article class="card mt-3">
      <div class="card-body">
        <h4><%= book.title %></h4>
        <p>ID: <%= book.id %></p>
        <p>Is Taken: <%= book.is_taken %></p>

        <section class="card-text">
          <time datetime="<%= book.formatted_created_at %>">
            <small><%= book.formatted_created_at %></small>
          </time>

          <p class="my-2">
            <%= book.body %>
          </p>
        </section>

        <%= link_to 'Show', book_path(book), class: 'btn btn-primary' %> 
        <%= button_to 'Take Book', take_book_path(book), method: :post, class: 'btn btn-success' if !book.is_taken %>
      </div>
    </article>
  <% end %>
<% else %>
  <p class="mt-3">There are no available books at the moment.</p>
  <p>Total books in database: <%= Book.count %></p>
  <p>Books marked as available: <%= Book.where(is_taken: [false, nil]).count %></p>
<% end %>

app/views/books/new.html.erb
<h1 class="mb-4">New book</h1>

<%= render 'form', book: @book %>

app/views/books/show.html.erb
<h1 class="mb-4"><%= @book.title %></h1>

<time datetime="<%= @book.formatted_created_at %>">
  <%= @book.formatted_created_at %>
</time>

<p class="lead my-3">
  <%= @book.body %>
</p>

<% if @book.is_taken %>
  <%= button_to 'Return Book', return_book_path(@book), method: :post, class: 'btn btn-warning' %>
<% else %>
  <%= button_to 'Take Book', take_book_path(@book), method: :post, class: 'btn btn-success' %>
<% end %>

<%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-secondary' %> |
<%= link_to 'Back', books_path, class: 'btn btn-primary' %>

app/views/home/index.html.erb
<div class="login-container">
<% if user_signed_in? %>
  <h1>Welcome, <%= current_user.email %></h1>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign in', new_user_session_path %>
  <%= link_to 'Sign up', new_user_registration_path %>
<% end %>
   
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>E library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-dark text-white">
    <header class="p-3 bg-danger text-white">
      <div class="container">
        <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><%= link_to 'Home', root_path, class: 'nav-link px-2 text-white' %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'Books', books_path, class: 'nav-link px-2 text-white' %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <main class="container mt-3">
      <% flash.each do |k, v| %>
        <%= tag.div v, class: "alert alert-#{k} bg-warning text-dark", role: 'alert' %>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<% @users.each do |user| %>
  <div>
    <%= link_to user.username, user_path(user) %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Books</h1>

<h2>Available Books</h2>
<% @available_books.each do |book| %>
  <div>
    <%= book.title %> by <%= book.author %>
    <%= button_to 'Take Book', take_book_user_path(@user, book_id: book.id), method: :post %>
  </div>
<% end %>

<h2>My Books</h2>
<% @my_books.each do |book| %>
  <div>
    <%= book.title %> by <%= book.author %>
    <%= button_to 'Return Book', return_book_user_path(@user, book_id: book.id), method: :post %>
  </div>
<% end %>